# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Work\Desktop\dialog_init.ui'
#
# Created: Mon Aug  5 11:57:51 2013
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox_dialog_init = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox_dialog_init.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox_dialog_init.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_dialog_init.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_dialog_init.setObjectName("buttonBox_dialog_init")
        self.widget = QtGui.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(30, 40, 162, 225))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_txt_objects = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_txt_objects.setFont(font)
        self.label_txt_objects.setObjectName("label_txt_objects")
        self.verticalLayout.addWidget(self.label_txt_objects)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_txt_nb_nodes = QtGui.QLabel(self.widget)
        self.label_txt_nb_nodes.setObjectName("label_txt_nb_nodes")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_txt_nb_nodes)
        self.spinBox_nb_nodes = QtGui.QSpinBox(self.widget)
        self.spinBox_nb_nodes.setObjectName("spinBox_nb_nodes")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.spinBox_nb_nodes)
        self.label_txt_nb_beacons = QtGui.QLabel(self.widget)
        self.label_txt_nb_beacons.setObjectName("label_txt_nb_beacons")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_txt_nb_beacons)
        self.spinBox_nb_beacons = QtGui.QSpinBox(self.widget)
        self.spinBox_nb_beacons.setObjectName("spinBox_nb_beacons")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.spinBox_nb_beacons)
        self.label_txt_vx = QtGui.QLabel(self.widget)
        self.label_txt_vx.setObjectName("label_txt_vx")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_txt_vx)
        self.doubleSpinBox_vx = QtGui.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_vx.setObjectName("doubleSpinBox_vx")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_vx)
        self.label_txt_vy = QtGui.QLabel(self.widget)
        self.label_txt_vy.setObjectName("label_txt_vy")
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_txt_vy)
        self.doubleSpinBox_vy = QtGui.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_vy.setObjectName("doubleSpinBox_vy")
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_vy)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.label_txt_env_size = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_txt_env_size.setFont(font)
        self.label_txt_env_size.setTextFormat(QtCore.Qt.AutoText)
        self.label_txt_env_size.setObjectName("label_txt_env_size")
        self.verticalLayout.addWidget(self.label_txt_env_size)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_txt_length = QtGui.QLabel(self.widget)
        self.label_txt_length.setObjectName("label_txt_length")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_txt_length)
        self.label_txt_width = QtGui.QLabel(self.widget)
        self.label_txt_width.setObjectName("label_txt_width")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_txt_width)
        self.spinBox_env_width = QtGui.QSpinBox(self.widget)
        self.spinBox_env_width.setObjectName("spinBox_env_width")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBox_env_width)
        self.spinBox_env_length = QtGui.QSpinBox(self.widget)
        self.spinBox_env_length.setObjectName("spinBox_env_length")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBox_env_length)
        self.verticalLayout.addLayout(self.formLayout)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox_dialog_init, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox_dialog_init, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_objects.setText(QtGui.QApplication.translate("Dialog", "Objects: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_nb_nodes.setText(QtGui.QApplication.translate("Dialog", "#nodes:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_nb_beacons.setText(QtGui.QApplication.translate("Dialog", "#beacons:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_vx.setText(QtGui.QApplication.translate("Dialog", "v_x:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_vy.setText(QtGui.QApplication.translate("Dialog", "v_y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_env_size.setText(QtGui.QApplication.translate("Dialog", "Environment size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_length.setText(QtGui.QApplication.translate("Dialog", "Length:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_width.setText(QtGui.QApplication.translate("Dialog", "Width:", None, QtGui.QApplication.UnicodeUTF8))

