# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Work\Desktop\dialog_init.ui'
#
# Created: Mon Aug 12 13:54:58 2013
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox_dialog_init = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox_dialog_init.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox_dialog_init.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox_dialog_init.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox_dialog_init.setObjectName("buttonBox_dialog_init")
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 40, 162, 232))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_txt_objects = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_txt_objects.setFont(font)
        self.label_txt_objects.setObjectName("label_txt_objects")
        self.verticalLayout.addWidget(self.label_txt_objects)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_txt_nb_nodes = QtGui.QLabel(self.layoutWidget)
        self.label_txt_nb_nodes.setObjectName("label_txt_nb_nodes")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_txt_nb_nodes)
        self.spinBox_nb_nodes = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_nb_nodes.setMaximum(1000)
        self.spinBox_nb_nodes.setProperty("value", 26)
        self.spinBox_nb_nodes.setObjectName("spinBox_nb_nodes")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.spinBox_nb_nodes)
        self.label_txt_nb_beacons = QtGui.QLabel(self.layoutWidget)
        self.label_txt_nb_beacons.setObjectName("label_txt_nb_beacons")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_txt_nb_beacons)
        self.spinBox_nb_beacons = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_nb_beacons.setMinimum(1)
        self.spinBox_nb_beacons.setProperty("value", 1)
        self.spinBox_nb_beacons.setObjectName("spinBox_nb_beacons")
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.spinBox_nb_beacons)
        self.label_txt_vx = QtGui.QLabel(self.layoutWidget)
        self.label_txt_vx.setObjectName("label_txt_vx")
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_txt_vx)
        self.doubleSpinBox_vx = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_vx.setObjectName("doubleSpinBox_vx")
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_vx)
        self.label_txt_vy = QtGui.QLabel(self.layoutWidget)
        self.label_txt_vy.setObjectName("label_txt_vy")
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_txt_vy)
        self.doubleSpinBox_vy = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_vy.setObjectName("doubleSpinBox_vy")
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_vy)
        self.label_txt_v_length = QtGui.QLabel(self.layoutWidget)
        self.label_txt_v_length.setObjectName("label_txt_v_length")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_txt_v_length)
        self.doubleSpinBox_v_length = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_v_length.setObjectName("doubleSpinBox_v_length")
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_v_length)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.label_txt_env_size = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_txt_env_size.setFont(font)
        self.label_txt_env_size.setTextFormat(QtCore.Qt.AutoText)
        self.label_txt_env_size.setObjectName("label_txt_env_size")
        self.verticalLayout.addWidget(self.label_txt_env_size)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_txt_length = QtGui.QLabel(self.layoutWidget)
        self.label_txt_length.setObjectName("label_txt_length")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_txt_length)
        self.label_txt_width = QtGui.QLabel(self.layoutWidget)
        self.label_txt_width.setObjectName("label_txt_width")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_txt_width)
        self.spinBox_env_width = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_env_width.setMaximum(530)
        self.spinBox_env_width.setSingleStep(10)
        self.spinBox_env_width.setProperty("value", 530)
        self.spinBox_env_width.setObjectName("spinBox_env_width")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.spinBox_env_width)
        self.spinBox_env_length = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox_env_length.setMaximum(410)
        self.spinBox_env_length.setSingleStep(10)
        self.spinBox_env_length.setProperty("value", 410)
        self.spinBox_env_length.setObjectName("spinBox_env_length")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.spinBox_env_length)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayoutWidget = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(210, 40, 160, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_txt_seed = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_txt_seed.setObjectName("label_txt_seed")
        self.horizontalLayout.addWidget(self.label_txt_seed)
        self.doubleSpinBox_seed = QtGui.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.doubleSpinBox_seed.setProperty("value", 1.0)
        self.doubleSpinBox_seed.setObjectName("doubleSpinBox_seed")
        self.horizontalLayout.addWidget(self.doubleSpinBox_seed)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox_dialog_init, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox_dialog_init, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_objects.setText(QtGui.QApplication.translate("Dialog", "Objects: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_nb_nodes.setText(QtGui.QApplication.translate("Dialog", "#nodes:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_nb_beacons.setText(QtGui.QApplication.translate("Dialog", "#beacons:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_vx.setText(QtGui.QApplication.translate("Dialog", "v_x:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_vy.setText(QtGui.QApplication.translate("Dialog", "v_y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_v_length.setText(QtGui.QApplication.translate("Dialog", "v_length", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_env_size.setText(QtGui.QApplication.translate("Dialog", "Environment size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_length.setText(QtGui.QApplication.translate("Dialog", "Length:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_width.setText(QtGui.QApplication.translate("Dialog", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_seed.setText(QtGui.QApplication.translate("Dialog", "seed:", None, QtGui.QApplication.UnicodeUTF8))

