# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Work\Desktop\window_main.ui'
#
# Created: Mon Aug 12 13:54:57 2013
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui
from gui.Widget_simulation_window import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")



         #OLD:
#         self.widget_simulation_window = QtGui.QWidget(self.centralwidget)
#         self.widget_simulation_window.setGeometry(QtCore.QRect(0, 0, 600, 450))
#         self.widget_simulation_window.setObjectName("widget_simulation_window")

        #NEW:
        self.widget_simulation_window = Widget_simulation_window(self.centralwidget)
        self.widget_simulation_window.setGeometry(QtCore.QRect(0, 0, 600, 450))
        self.widget_simulation_window.setObjectName("widget_simulation_window")

        
        
        
        self.graphicsView_sim = QtGui.QGraphicsView(self.widget_simulation_window)
        self.graphicsView_sim.setGeometry(QtCore.QRect(0, 0, 580, 450))
        self.graphicsView_sim.setObjectName("graphicsView_sim")
        
        
        


        self.formLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(590, 10, 201, 171))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_txt_node = QtGui.QLabel(self.formLayoutWidget)
        self.label_txt_node.setObjectName("label_txt_node")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_txt_node)
        self.label_node = QtGui.QLabel(self.formLayoutWidget)
        self.label_node.setText("")
        self.label_node.setObjectName("label_node")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_node)
        self.label_txt_layer = QtGui.QLabel(self.formLayoutWidget)
        self.label_txt_layer.setObjectName("label_txt_layer")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_txt_layer)
        self.label_layer = QtGui.QLabel(self.formLayoutWidget)
        self.label_layer.setText("")
        self.label_layer.setObjectName("label_layer")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_layer)
        self.label_txt_gateway = QtGui.QLabel(self.formLayoutWidget)
        self.label_txt_gateway.setObjectName("label_txt_gateway")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_txt_gateway)
        self.label_gateway = QtGui.QLabel(self.formLayoutWidget)
        self.label_gateway.setText("")
        self.label_gateway.setObjectName("label_gateway")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_gateway)
        self.label_txt_x = QtGui.QLabel(self.formLayoutWidget)
        self.label_txt_x.setObjectName("label_txt_x")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_txt_x)
        self.label_x = QtGui.QLabel(self.formLayoutWidget)
        self.label_x.setText("")
        self.label_x.setObjectName("label_x")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.label_x)
        self.label_txt_y = QtGui.QLabel(self.formLayoutWidget)
        self.label_txt_y.setObjectName("label_txt_y")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_txt_y)
        self.label_y = QtGui.QLabel(self.formLayoutWidget)
        self.label_y.setText("")
        self.label_y.setObjectName("label_y")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.label_y)
        self.label_txt_v_x = QtGui.QLabel(self.formLayoutWidget)
        self.label_txt_v_x.setObjectName("label_txt_v_x")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_txt_v_x)
        self.label_txt_v_y = QtGui.QLabel(self.formLayoutWidget)
        self.label_txt_v_y.setObjectName("label_txt_v_y")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_txt_v_y)
        self.label_v_x = QtGui.QLabel(self.formLayoutWidget)
        self.label_v_x.setText("")
        self.label_v_x.setObjectName("label_v_x")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.label_v_x)
        self.label_v_y = QtGui.QLabel(self.formLayoutWidget)
        self.label_v_y.setText("")
        self.label_v_y.setObjectName("label_v_y")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.label_v_y)
        self.checkBox_beacon = QtGui.QCheckBox(self.formLayoutWidget)
        self.checkBox_beacon.setObjectName("checkBox_beacon")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.checkBox_beacon)
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 470, 751, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_start_simulation = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_start_simulation.setObjectName("pushButton_start_simulation")
        self.horizontalLayout.addWidget(self.pushButton_start_simulation)
        self.pushButton_pause_simulation = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_pause_simulation.setObjectName("pushButton_pause_simulation")
        self.horizontalLayout.addWidget(self.pushButton_pause_simulation)
        self.pushButton_stop_simulation = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_stop_simulation.setObjectName("pushButton_stop_simulation")
        self.horizontalLayout.addWidget(self.pushButton_stop_simulation)
        self.label_speed = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_speed.setObjectName("label_speed")
        self.horizontalLayout.addWidget(self.label_speed)
        self.slider_simulation_speed = QtGui.QSlider(self.horizontalLayoutWidget)
        self.slider_simulation_speed.setOrientation(QtCore.Qt.Horizontal)
        self.slider_simulation_speed.setObjectName("slider_simulation_speed")
        self.horizontalLayout.addWidget(self.slider_simulation_speed)
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(610, 360, 160, 112))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_input_node = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_input_node.setObjectName("pushButton_input_node")
        self.verticalLayout.addWidget(self.pushButton_input_node)
        self.pushButton_delete_node = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_delete_node.setObjectName("pushButton_delete_node")
        self.verticalLayout.addWidget(self.pushButton_delete_node)
        self.pushButton_undelete_node = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_undelete_node.setObjectName("pushButton_undelete_node")
        self.verticalLayout.addWidget(self.pushButton_undelete_node)
        self.pushButton_crash_node = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_crash_node.setObjectName("pushButton_crash_node")
        self.verticalLayout.addWidget(self.pushButton_crash_node)
        self.listView_neighbours = QtGui.QListView(self.centralwidget)
        self.listView_neighbours.setGeometry(QtCore.QRect(590, 180, 201, 111))
        self.listView_neighbours.setObjectName("listView_neighbours")
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(590, 300, 201, 51))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_v_x = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_v_x.setObjectName("lineEdit_v_x")
        self.gridLayout.addWidget(self.lineEdit_v_x, 1, 1, 1, 1)
        self.lineEdit_v_y = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_v_y.setObjectName("lineEdit_v_y")
        self.gridLayout.addWidget(self.lineEdit_v_y, 2, 1, 1, 1)
        self.label_txt_v_x_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_txt_v_x_2.setObjectName("label_txt_v_x_2")
        self.gridLayout.addWidget(self.label_txt_v_x_2, 1, 0, 1, 1)
        self.label_txt_v_y_2 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_txt_v_y_2.setObjectName("label_txt_v_y_2")
        self.gridLayout.addWidget(self.label_txt_v_y_2, 2, 0, 1, 1)
        self.pushButton_input_v = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_input_v.setObjectName("pushButton_input_v")
        self.gridLayout.addWidget(self.pushButton_input_v, 2, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuAcoustic_Network_Simulation = QtGui.QMenu(self.menubar)
        self.menuAcoustic_Network_Simulation.setObjectName("menuAcoustic_Network_Simulation")
        self.menuSimulation = QtGui.QMenu(self.menubar)
        self.menuSimulation.setObjectName("menuSimulation")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionVersion = QtGui.QAction(MainWindow)
        self.actionVersion.setObjectName("actionVersion")
        self.actionINIT = QtGui.QAction(MainWindow)
        self.actionINIT.setObjectName("actionINIT")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionNewSim = QtGui.QAction(MainWindow)
        self.actionNewSim.setObjectName("actionNewSim")
        self.menuAcoustic_Network_Simulation.addAction(self.actionHelp)
        self.menuAcoustic_Network_Simulation.addAction(self.actionAbout)
        self.menuSimulation.addAction(self.actionNewSim)
        self.menuSimulation.addAction(self.actionINIT)
        self.menubar.addAction(self.menuSimulation.menuAction())
        self.menubar.addAction(self.menuAcoustic_Network_Simulation.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Multi hop ad hoc acoustic network simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_node.setText(QtGui.QApplication.translate("MainWindow", "node:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_layer.setText(QtGui.QApplication.translate("MainWindow", "layer:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_gateway.setText(QtGui.QApplication.translate("MainWindow", "gateway:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_x.setText(QtGui.QApplication.translate("MainWindow", "x:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_y.setText(QtGui.QApplication.translate("MainWindow", "y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_v_x.setText(QtGui.QApplication.translate("MainWindow", "v_x:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_v_y.setText(QtGui.QApplication.translate("MainWindow", "v_y:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_beacon.setText(QtGui.QApplication.translate("MainWindow", "beacon", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_start_simulation.setText(QtGui.QApplication.translate("MainWindow", "start simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_pause_simulation.setText(QtGui.QApplication.translate("MainWindow", "pause", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_stop_simulation.setText(QtGui.QApplication.translate("MainWindow", "stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_speed.setText(QtGui.QApplication.translate("MainWindow", "speed", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_input_node.setText(QtGui.QApplication.translate("MainWindow", "input node", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_delete_node.setText(QtGui.QApplication.translate("MainWindow", "delete node", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_undelete_node.setText(QtGui.QApplication.translate("MainWindow", "undelete node", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_crash_node.setText(QtGui.QApplication.translate("MainWindow", "crash node", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_v_x_2.setText(QtGui.QApplication.translate("MainWindow", "v_x:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_txt_v_y_2.setText(QtGui.QApplication.translate("MainWindow", "v_y:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_input_v.setText(QtGui.QApplication.translate("MainWindow", "input", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAcoustic_Network_Simulation.setTitle(QtGui.QApplication.translate("MainWindow", "?", None, QtGui.QApplication.UnicodeUTF8))
        self.menuSimulation.setTitle(QtGui.QApplication.translate("MainWindow", "simulation", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVersion.setText(QtGui.QApplication.translate("MainWindow", "Version", None, QtGui.QApplication.UnicodeUTF8))
        self.actionINIT.setText(QtGui.QApplication.translate("MainWindow", "INIT", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNewSim.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))

import images.robots_rc
